title: Goblin Wars
description: A simple GitHub Pages test site
theme: minima
baseurl: ""     # leave empty for user site; use "/REPO" for project sites
url: "https://goblinwars.github.io"
markdown: kramdown
permalink: /:title/
exclude:

Gemfile
node_modules
